version: "3"
services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        expose:
            - 3000
        ports:
            - 3000:3000
        image: agarioclone_agar
        container_name: agarioclone_agar
        volumes:
            - ./test:/root/src/app/test
            - ./src:/root/src/app/src
        tty: true
